---
- name: Установка стандартных пакетов
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    lock_timeout: 300
  loop: 
    - "{{ packages_to_install }}"

# Скачивание и установка Wiki
- name: Скачивание MediaWiki
  ansible.builtin.get_url:
    url: https://releases.wikimedia.org/mediawiki/1.46/mediawiki-1.46.0.tar.gz
    dest: /tmp/MediaWiki.tar.gz

- name: Создание директории сервера MediaWiki
  ansible.builtin.file:
    path: /var/lib/mediawiki
    state: directory

- name: Извлечение архива MediaWiki
  become: true
  ansible.builtin.unarchive:
    src: /tmp/MediaWiki.tar.gz
    dest: /var/lib/mediawiki
    remote_src: true


# Настройка MySQL
# - name: Создание баы данных MySQL
#   community.mysql.mysql_db:
#     name: my_wiki
#     state: present
#     login_user: root
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     # Если пользователь требует пароль, 
#     # то можно убрать сокет и добавляем: 
#     # login_password: "pass123"

# - name: Создание пользователя MySQL
#   community.mysql.mysql_user:
#     name: wikiuser
#     password: pass123    #Обязательно заменить пароль
#     priv: "my_wiki.*:ALL"
#     state: present
#     login_user: root
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     # Если пользователь требует пароль, 
#     # то можно убрать сокет и добавляем: 
#     # login_password: "pass123"

# Настройка PostgreSQL
- name: Создание базы данных PostgreSQL
  community.postgresql.postgresql_db:
    name: my_wiki
    state: present
    login_user: postgres
  become: true
  become_user: postgres

- name: Создание пользователя PostgreSQL
  community.postgresql.postgresql_user:
    name: wikiuser
    password: "pass123"
    db: my_wiki
    priv: "ALL"
    state: present
    login_user: postgres
  become: true
  become_user: postgres

- name: Изменение владельца Базы Данных
  community.postgresql.postgresql_db:
    name: my_wiki
    owner: wikiuser
    state: present
  become: true
  become_user: postgres


# sudo ln -s /var/lib/mediawiki /var/www/html/mediawiki
- name: Создание символической ссылки для MediaWiki
  ansible.builtin.file:
    src: /var/lib/mediawiki
    dest: /var/www/html/mediawiki 
    state: link
  become: true

- name: Ссылка
  ansible.builtin.debug:
    msg: "Ссылка на главную MediaWiki: http://{{item['ansible_host']}}/mediawiki/mediawiki-1.46.0/"
  loop: 
    - "{{ hostvars }}"